title: "Tech Mining: applying text mining methods to technical documents"
date: 2021-02-22
author: Soujanya Dash
email: soujda2000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tech Mining makes exploitation of text databases meaningful to those who can gain from derived knowledge about emerging technologies. 
  The methodology is almost similar to usual mining process.
  First: We need to choose the right source. For instance, if we want patent informations about medical issues like cancer, we would probably want to go for the MEDLINE database.
  Second: We form queries by broadening and narrowing the searches for precision and recall.
  Third: After the selected articles are chosen, we do the analysis. The details will be mentioned later.

# social links
twitter_username: NA # DO NOT include the @ character, or else the build will fail!
github_username:  Soujanya0506 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
